CREATE DATABASE IF NOT EXISTS hr_company CHARACTER SET utf8 COLLATE utf8_general_ci;

use hr_company;

CREATE TABLE perfiles (
id INT NOT NULL AUTO_INCREMENT,
perfil VARCHAR(30),
PRIMARY KEY (id),
UNIQUE KEY perfil (perfil)
)ENGINE=INNODB;

CREATE TABLE usuarios (
id INT NOT NULL AUTO_INCREMENT,
perfil_id INT NOT NULL,
estado ENUM("Activo","Inactivo") NOT NULL,
nombre VARCHAR(50) NOT NULL,
apellido VARCHAR(50) NOT NULL,
telefono VARCHAR(20) NOT NULL,
email VARCHAR(100) NOT NULL,
password VARCHAR(150) NOT NULL,
img LONGBLOB NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
PRIMARY KEY (id),
CONSTRAINT fk_perfiles
FOREIGN KEY (perfil_id)
REFERENCES perfiles (id)
)ENGINE=INNODB;


CREATE TABLE clientes (
id INT NOT NULL AUTO_INCREMENT,
empresa VARCHAR(100) NOT NULL,
responsable_proceso VARCHAR(100) NOT NULL,
email VARCHAR(50) NOT NULL,
telefono VARCHAR(20) NOT NULL,
direccion VARCHAR(100) NOT NULL,
referencia_ubicacion VARCHAR(100) NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
PRIMARY KEY (id)
)ENGINE=INNODB;

CREATE TABLE ven_vacantes (
id INT NOT NULL AUTO_INCREMENT,
cliente_id INT NOT NULL,
puesto VARCHAR(50) NOT NULL,
vacantes INT NOT NULL,
fecha_solicitud DATETIME NOT NULL,
servicio VARCHAR(50) NOT NULL,
duracion VARCHAR(20) NOT NULL,
modalidad VARCHAR(20) NOT NULL,
horario VARCHAR(20) NOT NULL,
encargado VARCHAR(50) NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
PRIMARY KEY (id),
CONSTRAINT fk_cliente_id
FOREIGN KEY (cliente_id)
REFERENCES clientes (id)
)ENGINE=INNODB;

CREATE TABLE ven_personal (
id INT NOT NULL AUTO_INCREMENT,
vacante_id INT NOT NULL,
rango_edad VARCHAR(20) NOT NULL,
sexo VARCHAR(10) NOT NULL,
estado_civil VARCHAR(10) NOT NULL,
lugar_residencia VARCHAR(30) NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
PRIMARY KEY (id),
CONSTRAINT fk_vacante_id
FOREIGN KEY (vacante_id)
REFERENCES ven_vacantes(id)
)ENGINE=INNODB;

CREATE TABLE rec_candidatos (
id INT NOT NULL AUTO_INCREMENT,
fecha_alta TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
codigo INT NOT NULL,
nombres VARCHAR(50) NOT NULL,
apellidos VARCHAR(50) NOT NULL,
edad INT NOT NULL,
telefono VARCHAR(20) NOT NULL,
email VARCHAR(50) NOT NULL,
ciudad VARCHAR(40) NOT NULL,
prestaciones VARCHAR(20) NOT NULL,
tipo_perfil VARCHAR(20) NOT NULL,
especialidad VARCHAR(50) NOT NULL,
experiencia VARCHAR(10) NOT NULL,
updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
PRIMARY KEY (id)
)ENGINE=INNODB;

CREATE TABLE historial_login (
id INT NOT NULL AUTO_INCREMENT,
email VARCHAR(50) NOT NULL,
password VARCHAR(150) NOT NULL,
status VARCHAR(10) NOT NULL,
fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
ip VARCHAR(30) NOT NULL,
PRIMARY KEY (id)
)ENGINE=INNODB;

CREATE TABLE usuarios_token (
id INT NOT NULL AUTO_INCREMENT,
email VARCHAR(50) NOT NULL,
token VARCHAR(100) NOT NULL,
PRIMARY KEY (id)
)ENGINE=INNODB;


CREATE TABLE rec_pago (
id INT NOT NULL AUTO_INCREMENT,
vacante_id INT NOT NULL,
sueldo_bruto DECIMAL(13,4) NOT NULL,
sueldo_neto DECIMAL(13,4) NOT NULL,
forma_pago VARCHAR(30) NOT NULL,
descuento VARCHAR(10) NOT NULL,
cta_bancaria VARCHAR(20) NOT NULL,
cta_interbancaria VARCHAR(30) NOT NULL,
banco VARCHAR(40) NOT NULL,
created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (id),
CONSTRAINT fk_vacante_id
FOREIGN KEY (vacante_id)
REFERENCES v_vacantes (id)
)ENGINE=INNODB;